[package]
name = "coding-interviews"
version = "0.1.0"
authors = ["mutexlock <xiebei1108@outlook.com>"]
edition = "2018"

[dependencies]
docopt = "1"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`